image: node:16-alpine

services:
  - postgres:13-alpine

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: 1234
  POSTGRES_HOST_AUTH_METHOD: trust

cache:
  paths:
    - node_modules/

stages:
  - linter
  - build
  - test

linter-job:
  stage: linter
  script:
    - npm install
    - npm run lint

build-job:
  stage: build
  script:
    - npm install
    - npm run build

test-job:
  stage: test
  script:
    - cp template.env .env
    - npm install
    - npm run test:e2e
    - npm run test
