version: '3.9'

services:
  db:
    image: postgres:13-alpine
    container_name: db-hackernews-node
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db-node:/var/lib/postgresql/data

  api:
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm start
    image: node:16-alpine
    container_name: api-hackernews-node
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=db-hackernews-node
      - DB_USER=admin
      - DB_PASSWORD=1234
      - DB_LOGGIN=false
    ports:
      - 4000:$PORT
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # networks:
    #   - net-api
    # depends_on:
    #   - db

volumes:
  db-node:
