version: '3.9'

services:
  db:
    image: postgres:13-alpine
    container_name: db-node
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - database:/var/lib/postgresql/data

  api:
    build:
      context: .
      target: $NODE_ENV
      dockerfile: ./Dockerfile
    command: npm run start:dev
    image: node:16-alpine
    container_name: api-node
    restart: unless-stopped
    env_file: .env
    ports:
      - $PORT:$PORT
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

volumes:
  database:
